# Generated by Django 4.1.3 on 2022-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareplan',
            name='card_front',
            field=models.ImageField(default=None, upload_to='insurance_cards_images/'),
        ),
    ]
