# Generated by Django 4.1.2 on 2022-10-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PATIENT', 'patient'), ('TECHNICIAN', 'TECHNICIAN')], max_length=50),
        ),
    ]
