# Generated by Django 4.1.2 on 2022-10-17 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='health_care_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.healthcareplan'),
        ),
    ]
