# Generated by Django 4.1.3 on 2022-12-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
        ('app', '0003_alter_test_description_alter_test_requirements'),
    ]

    operations = [
    ]
