# Generated by Django 4.1.2 on 2022-10-17 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('requirements', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.CharField(choices=[('ACCEPTED', 'accepted'), ('DECLINED', 'declined'), ('PENDING', 'pending')], max_length=50)),
                ('lab_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_technician', to=settings.AUTH_USER_MODEL)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.labtest')),
                ('lab_test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testrequest')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employer_lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.laboratory'),
        ),
    ]
